# Generated by Django 3.1.5 on 2021-01-13 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Спецификация',
                'verbose_name_plural': 'Спецификация',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='место отбора пробы', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компания',
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Тип образца',
                'verbose_name_plural': 'Тип образца',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукт',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.SlugField(unique=True, verbose_name='образец')),
                ('date_production', models.DateField(verbose_name='дата производства')),
                ('bb_from', models.PositiveIntegerField(blank=True, verbose_name='Б.Б с')),
                ('bb_to', models.PositiveIntegerField(blank=True, verbose_name='Б.Б по')),
                ('pallet_from', models.PositiveIntegerField(blank=True, verbose_name='паллеты с')),
                ('pallet_to', models.PositiveIntegerField(blank=True, verbose_name='паллеты по')),
                ('date_registration', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
                ('repeate', models.BooleanField(verbose_name='повтор')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('category', models.ManyToManyField(to='lims.Category', verbose_name='спецификация')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.company', verbose_name='компания')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.materialtype', verbose_name='вид образца')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.producttype', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'Образец',
                'verbose_name_plural': 'Образцы',
            },
        ),
    ]
