# Generated by Django 3.1.5 on 2021-01-28 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_auto_20210128_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.color', verbose_name='цвет этикетки'),
        ),
    ]
