# Generated by Django 3.1.5 on 2021-01-30 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0003_auto_20210128_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(max_length=5, verbose_name='смена')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смена',
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='work_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.workshift', verbose_name='смена'),
        ),
    ]
