# Generated by Django 3.1.5 on 2021-01-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0004_auto_20210130_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshift',
            name='value',
            field=models.IntegerField(verbose_name='смена'),
        ),
    ]
