# Generated by Django 3.1.5 on 2021-01-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0004_auto_20210113_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='category',
            field=models.ManyToManyField(blank=True, to='lims.Category', verbose_name='спецификация'),
        ),
    ]
