# Generated by Django 3.1.5 on 2021-02-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0005_auto_20210130_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='samples', to='lims.Category', verbose_name='категория'),
        ),
    ]
