# Generated by Django 3.1.5 on 2021-02-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0006_auto_20210201_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('ffa_min', models.FloatField(blank=True, null=True, verbose_name='кислотное число мин. значение')),
                ('ffa_max', models.FloatField(blank=True, null=True, verbose_name='кислотное число макс. значение')),
                ('protein_min', models.FloatField(blank=True, null=True, verbose_name='протеин мин. значение')),
                ('protein_max', models.FloatField(blank=True, null=True, verbose_name='пртоеин макс. значение')),
                ('fat_min', models.FloatField(blank=True, null=True, verbose_name='жир мин. значение')),
                ('fat_max', models.FloatField(blank=True, null=True, verbose_name='жир макс. значение')),
                ('ash_min', models.FloatField(blank=True, null=True, verbose_name='зола мин. значение')),
                ('ash_max', models.FloatField(blank=True, null=True, verbose_name='зола макс. значение')),
                ('pv_min', models.FloatField(blank=True, null=True, verbose_name=' перекисное число мин. значение')),
                ('pv_max', models.FloatField(blank=True, null=True, verbose_name='перекисное число макс. значение')),
                ('aoks_min', models.FloatField(blank=True, null=True, verbose_name='антиоксидант мин. значение')),
                ('aoks_max', models.FloatField(blank=True, null=True, verbose_name='антиоксидант макс. значение')),
            ],
        ),
    ]
