# Generated by Django 3.1.5 on 2021-01-14 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0006_fat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='samples', to='lims.Category', verbose_name='спецификация'),
        ),
        migrations.CreateModel(
            name='Bruker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ffa', models.FloatField(blank=True, null=True, verbose_name='кислотное число')),
                ('protein', models.FloatField(blank=True, null=True, verbose_name='протеин')),
                ('fat', models.FloatField(blank=True, null=True, verbose_name='жир')),
                ('ash', models.FloatField(blank=True, null=True, verbose_name='зола')),
                ('moisture', models.FloatField(blank=True, null=True, verbose_name='влага')),
                ('date_pub', models.DateTimeField(auto_now=True, verbose_name='дата анализа')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brukers', to='lims.sample', verbose_name='образец')),
            ],
        ),
    ]
