# Generated by Django 3.1.5 on 2021-02-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0007_specification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='specification',
            options={'verbose_name': 'Спецификация', 'verbose_name_plural': 'Спецификация'},
        ),
        migrations.AddField(
            model_name='sample',
            name='specification',
            field=models.ManyToManyField(blank=True, related_name='samples', to='lims.Specification'),
        ),
    ]
