# Generated by Django 3.1.5 on 2021-01-17 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0007_auto_20210114_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bruker',
            options={'verbose_name': 'Спектрометр', 'verbose_name_plural': 'Спектрометр'},
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_mass', models.FloatField(blank=True, max_length=5, null=True, verbose_name='масса навески')),
                ('titrant_volume', models.FloatField(blank=True, null=True, verbose_name='объем 0.2 М серной кислоты')),
                ('value', models.FloatField(blank=True, max_length=4, null=True, verbose_name='массовая доля сырого протеина')),
                ('date_pub', models.DateTimeField(auto_now=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proteins', to='lims.sample', verbose_name='образец')),
            ],
            options={
                'verbose_name': 'Протеин',
                'verbose_name_plural': 'Протеин',
            },
        ),
    ]
