# Generated by Django 3.1.5 on 2021-01-18 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0008_auto_20210117_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank_cup_mass', models.FloatField(blank=True, null=True, verbose_name='масса пустогй бюксы')),
                ('sample_mass', models.FloatField(blank=True, null=True, verbose_name='масса навески')),
                ('final_cup_mass', models.FloatField(blank=True, null=True, verbose_name='масса бюксы i')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='массовая доля сырой золы')),
                ('date_pub', models.DateTimeField(auto_now=True, verbose_name='дата анализа')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ashs', to='lims.sample', verbose_name='образец')),
            ],
            options={
                'verbose_name': 'Зола',
                'verbose_name_plural': 'Зола',
            },
        ),
    ]
