# Generated by Django 3.1.5 on 2021-01-18 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0009_ash'),
    ]

    operations = [
        migrations.CreateModel(
            name='FFA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_mass', models.FloatField(blank=True, max_length=5, null=True, verbose_name='масса навески')),
                ('titrant_volume', models.FloatField(blank=True, null=True, verbose_name='объем 0.1 Н KOH')),
                ('value', models.FloatField(blank=True, max_length=4, null=True, verbose_name='кислотное число')),
                ('date_pub', models.DateTimeField(auto_now=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ffas', to='lims.sample', verbose_name='образец')),
            ],
            options={
                'verbose_name': 'Кислотное число',
                'verbose_name_plural': 'Кислотное число',
            },
        ),
    ]
