# Generated by Django 3.1.5 on 2021-01-18 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0010_ffa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ash',
            name='blank_cup_mass',
            field=models.FloatField(blank=True, null=True, verbose_name='масса пустого тигля'),
        ),
        migrations.AlterField(
            model_name='ash',
            name='final_cup_mass',
            field=models.FloatField(blank=True, null=True, verbose_name='масса тигля i'),
        ),
        migrations.CreateModel(
            name='Moisture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank_cup_mass', models.FloatField(blank=True, null=True, verbose_name='масса пустой бюксы')),
                ('sample_mass', models.FloatField(blank=True, null=True, verbose_name='масса навески')),
                ('final_cup_mass', models.FloatField(blank=True, null=True, verbose_name='масса бюксы i')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='массовая доля влаги')),
                ('date_pub', models.DateTimeField(auto_now=True, verbose_name='дата анализа')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moistures', to='lims.sample', verbose_name='образец')),
            ],
            options={
                'verbose_name': 'Влага',
                'verbose_name_plural': 'Влага',
            },
        ),
    ]
