# Generated by Django 3.2.7 on 2021-09-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0010_aoks_ash_bruker_category_color_company_fat_ffa_materialtype_moisture_producttype_protein_sample_spec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='specification',
        ),
        migrations.AlterField(
            model_name='workshift',
            name='value',
            field=models.IntegerField(unique=True, verbose_name='смена'),
        ),
    ]
