# Generated by Django 3.1.5 on 2021-01-18 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0011_auto_20210118_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aoks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_mass', models.FloatField(blank=True, null=True, verbose_name='масса навески')),
                ('bha', models.FloatField(blank=True, null=True)),
                ('bht', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True, verbose_name='суммарно bha/bht')),
                ('date_pub', models.DateTimeField(auto_now=True, verbose_name='дата анализа')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aoks', to='lims.sample', verbose_name='образец')),
            ],
            options={
                'verbose_name': 'Антиоксидант',
                'verbose_name_plural': 'Антиоксидант',
            },
        ),
    ]
