# Generated by Django 3.2.7 on 2021-09-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0011_auto_20210915_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='photo',
            field=models.ImageField(blank=True, upload_to='magages/%Y/%m/%d/', verbose_name='фото'),
        ),
    ]
