# Generated by Django 3.2.7 on 2021-09-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0017_aoks_ash_bruker_category_color_company_fat_ffa_materialtype_moisture_producttype_protein_sample_spec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialtype',
            options={'verbose_name': 'Вид образца', 'verbose_name_plural': 'Вид образца'},
        ),
        migrations.AddField(
            model_name='aoks',
            name='date_time_result',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время результата'),
        ),
        migrations.AddField(
            model_name='aoks',
            name='technical_information',
            field=models.CharField(blank=True, help_text='для внутреннего использования', max_length=150, verbose_name='тех. инфо'),
        ),
        migrations.AddField(
            model_name='ash',
            name='date_time_result',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время результата'),
        ),
        migrations.AddField(
            model_name='ash',
            name='technical_information',
            field=models.CharField(blank=True, help_text='для внутреннего использования', max_length=150, verbose_name='тех. инфо'),
        ),
        migrations.AddField(
            model_name='fat',
            name='date_time_result',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время результата'),
        ),
        migrations.AddField(
            model_name='fat',
            name='technical_information',
            field=models.CharField(blank=True, help_text='для внутреннего использования', max_length=150, verbose_name='тех. инфо'),
        ),
        migrations.AddField(
            model_name='ffa',
            name='technical_information',
            field=models.CharField(blank=True, help_text='для внутреннего использования', max_length=150, verbose_name='тех. инфо'),
        ),
        migrations.AddField(
            model_name='moisture',
            name='date_time_result',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время результата'),
        ),
        migrations.AddField(
            model_name='moisture',
            name='technical_information',
            field=models.CharField(blank=True, help_text='для внутреннего использования', max_length=150, verbose_name='тех. инфо'),
        ),
        migrations.AddField(
            model_name='protein',
            name='date_time_result',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время результата'),
        ),
        migrations.AddField(
            model_name='protein',
            name='technical_information',
            field=models.CharField(blank=True, help_text='для внутреннего использования', max_length=150, verbose_name='тех. инфо'),
        ),
        migrations.AlterField(
            model_name='ffa',
            name='date_time_result',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время результата'),
        ),
    ]
