# Generated by Django 3.2.7 on 2021-09-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0018_auto_20210915_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aoks',
            name='date_time_result',
        ),
        migrations.RemoveField(
            model_name='ash',
            name='date_time_result',
        ),
        migrations.RemoveField(
            model_name='fat',
            name='date_time_result',
        ),
        migrations.RemoveField(
            model_name='ffa',
            name='date_time_result',
        ),
        migrations.RemoveField(
            model_name='moisture',
            name='date_time_result',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='date_time_result',
        ),
    ]
