# Generated by Django 3.2.7 on 2021-09-28 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0021_aoks_ash_bruker_color_company_fat_ffa_material_moisture_product_protein_sample_specification_tag_wor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_5mm', models.FloatField(blank=True, null=True, verbose_name='5 мм')),
                ('value_4mm', models.FloatField(blank=True, null=True, verbose_name='4 мм')),
                ('value_3mm', models.FloatField(blank=True, null=True, verbose_name='3 мм')),
                ('value_2mm', models.FloatField(blank=True, null=True, verbose_name='2 мм')),
                ('value_1mm', models.FloatField(blank=True, null=True, verbose_name='1 мм')),
                ('sample_mass', models.FloatField(blank=True, null=True, verbose_name='масса обрзца')),
                ('mass_5mm', models.FloatField(blank=True, null=True, verbose_name='масса 5 мм')),
                ('mass_4mm', models.FloatField(blank=True, null=True, verbose_name='масса 4 мм')),
                ('mass_3mm', models.FloatField(blank=True, null=True, verbose_name='масса 3 мм')),
                ('mass_2mm', models.FloatField(blank=True, null=True, verbose_name='масса 2 мм')),
                ('mass_1mm', models.FloatField(blank=True, null=True, verbose_name='масса 1 мм')),
                ('free_meal', models.FloatField(blank=True, null=True, verbose_name='чистая мука')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='millings', to='lims.sample', verbose_name='образец')),
            ],
            options={
                'verbose_name': 'Крупность помола',
                'verbose_name_plural': 'Крупность помола',
            },
        ),
    ]
