# Generated by Django 3.2.7 on 2021-09-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0022_milling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milling',
            name='free_meal',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='чистая мука'),
        ),
        migrations.AlterField(
            model_name='milling',
            name='mass_1mm',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='масса 1 мм'),
        ),
        migrations.AlterField(
            model_name='milling',
            name='mass_2mm',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='масса 2 мм'),
        ),
        migrations.AlterField(
            model_name='milling',
            name='mass_3mm',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='масса 3 мм'),
        ),
        migrations.AlterField(
            model_name='milling',
            name='mass_4mm',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='масса 4 мм'),
        ),
        migrations.AlterField(
            model_name='milling',
            name='mass_5mm',
            field=models.FloatField(default=0, verbose_name='масса 5 мм'),
        ),
        migrations.AlterField(
            model_name='milling',
            name='sample_mass',
            field=models.FloatField(blank=True, null=True, verbose_name='масса образца'),
        ),
    ]
