# Generated by Django 3.2.7 on 2021-09-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0023_auto_20210928_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='milling',
            name='mass_free_meal',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='чистая мука'),
        ),
        migrations.AlterField(
            model_name='milling',
            name='free_meal',
            field=models.FloatField(blank=True, null=True, verbose_name='чистая мука'),
        ),
    ]
