# Generated by Django 3.2.7 on 2021-09-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0024_auto_20210928_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milling',
            name='mass_free_meal',
        ),
        migrations.AlterField(
            model_name='milling',
            name='free_meal',
            field=models.FloatField(blank=True, null=True, verbose_name='чистая мука % '),
        ),
        migrations.AlterField(
            model_name='milling',
            name='mass_1mm',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='масса 1 мм г.'),
        ),
        migrations.AlterField(
            model_name='milling',
            name='mass_2mm',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='масса 2 мм г.'),
        ),
        migrations.AlterField(
            model_name='milling',
            name='mass_3mm',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='масса 3 мм г.'),
        ),
        migrations.AlterField(
            model_name='milling',
            name='mass_4mm',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='масса 4 мм г.'),
        ),
        migrations.AlterField(
            model_name='milling',
            name='mass_5mm',
            field=models.FloatField(default=0, verbose_name='масса 5 мм г.'),
        ),
        migrations.AlterField(
            model_name='milling',
            name='sample_mass',
            field=models.FloatField(blank=True, null=True, verbose_name='масса образца г.'),
        ),
        migrations.AlterField(
            model_name='milling',
            name='value_1mm',
            field=models.FloatField(blank=True, null=True, verbose_name='1 мм %'),
        ),
        migrations.AlterField(
            model_name='milling',
            name='value_2mm',
            field=models.FloatField(blank=True, null=True, verbose_name='2 мм %'),
        ),
        migrations.AlterField(
            model_name='milling',
            name='value_3mm',
            field=models.FloatField(blank=True, null=True, verbose_name='3 мм %'),
        ),
        migrations.AlterField(
            model_name='milling',
            name='value_4mm',
            field=models.FloatField(blank=True, null=True, verbose_name='4 мм %'),
        ),
        migrations.AlterField(
            model_name='milling',
            name='value_5mm',
            field=models.FloatField(blank=True, null=True, verbose_name='5 мм %'),
        ),
    ]
