# Generated by Django 3.2.7 on 2021-09-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0025_auto_20210928_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_mass', models.FloatField(blank=True, default=500, null=True, verbose_name='масса навески в г.')),
                ('mmp_mass', models.FloatField(blank=True, null=True, verbose_name='масса ММП в г.')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='значение ММП в мг/кг.')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mmps', to='lims.sample', verbose_name='образец')),
            ],
            options={
                'verbose_name': 'ММП',
                'verbose_name_plural': 'ММП',
            },
        ),
    ]
