# Generated by Django 3.2.7 on 2021-09-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0026_mmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='milling',
            name='date_pub',
            field=models.DateTimeField(auto_now=True, verbose_name='дата анализа'),
        ),
        migrations.AddField(
            model_name='mmp',
            name='date_pub',
            field=models.DateTimeField(auto_now=True, verbose_name='дата анализа'),
        ),
    ]
